modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/sleepy-evelyn/Block-Claims/issues"
license = "MIT"

[[mods]]
modId = "blockclaims"
version = "${version}"
displayName = "Block Claims"
authors = "SleepyEvelyn"
description = '''
A wrapper for claims mods that allows you to claim, configure and sell land with simple blocks
'''
#logoFile = ""

[[dependencies.blockclaims]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockclaims]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockclaims]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "blockclaims.mixins.json"
