modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/sleepy-evelyn/Block-Claims/issues"
license = "MIT"

[[mods]]
modId = "territorial"
version = "${version}"
displayName = "Territorial Block Claims"
authors = "SleepyEvelyn"
description = '''
A wrapper for claims mods that allows you to claim, configure and sell land with simple blocks
'''
#logoFile = ""

[[dependencies.territorial]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.territorial]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.territorial]]
modId = "fzzy_config"
type = "required"
versionRange = "[0.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "territorial.mixins.json"
